import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import React from "react"
import { AntdRegistry } from "@ant-design/nextjs-registry"
import { ConfigProvider } from "antd"
import theme from "@/theme"
import { NtLayout } from "@/components"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={(inter.className, "theme-origin")}>
				<AntdRegistry>
					<ConfigProvider theme={theme}>
						<NtLayout>{children}</NtLayout>
					</ConfigProvider>
				</AntdRegistry>
			</body>
		</html>
	)
}
